---
- name: Add hummingbird user
  user: 
    name: hummingbird
    createhome: no
    system: yes
- name: Install memcache
  apt:
    name: memcached
    state: present
- name: Configure memcached
  lineinfile:
    path: /etc/memcached.conf
    regexp: '^127\.0\.0\.1'
    line: '-l {{ service_ip }}'
- name: Restart memcached
  service:
    enabled: yes
    name: memcached
    state: restarted
- name: Install curl
  apt:
    name: curl
    state: present
- name: Install jq
  apt:
    name: jq
    state: present
- name: Find latest hummingbird binary
  shell: curl -s https://api.github.com/repos/troubling/hummingbird/releases/latest | jq --raw-output '.assets[0] | .browser_download_url'
  when: hummingbird_version is not defined or hummingbird_version == ''
  register: hummingbird_binary_url
- name: Create download tmp dir
  tempfile:
    state: directory
  register: downloadtmpdir
- name: Download latest hummingbird binary
  get_url:
    url: "{{ hummingbird_binary_url.stdout }}"
    dest: "{{downloadtmpdir.path}}/hummingbird"
    mode: 0755
    force: yes
  when: not hummingbird_binary_url|skipped
- name: Download specific hummingbird binary
  get_url:
    url: "https://github.com/troubling/hummingbird/releases/download/{{hummingbird_version}}/hummingbird"
    dest: "{{downloadtmpdir.path}}/hummingbird"
    mode: 0755
    force: yes
  when: hummingbird_binary_url|skipped
- name: Move binary into place
  copy:
    remote_src: yes
    src: "{{downloadtmpdir.path}}/hummingbird"
    dest: /usr/local/bin/hummingbird
    mode: 0755
    force: yes
- name: Remove temp dir
  file:
    state: absent
    path: "{{downloadtmpdir.path}}"
- name: Create /etc/hummingbird
  file:
    path: /etc/hummingbird
    state: directory
    mode: 0755
    owner: hummingbird
    group: hummingbird
- name: Copy /etc/hummingbird/hummingbird.conf
  template:
    src: etc/hummingbird.conf.j2
    dest: /etc/hummingbird/hummingbird.conf
    mode: 0644
    owner: hummingbird
    group: hummingbird
- name: Create /var/cache/swift
  file:
    path: /var/cache/swift
    state: directory
    mode: 0755
    owner: hummingbird
    group: hummingbird
- name: Create /var/log/hummingbird
  file:
    path: /var/log/hummingbird
    state: directory
    mode: 0755
    owner: syslog
    group: adm
- name: Install rsyslog
  apt:
    name: rsyslog
    state: present
- name: Copy rsyslog config
  copy:
    src: rsyslog.d/20-hbird.conf
    dest: /etc/rsyslog.d/20-hbird.conf
    mode: 0644
- name: Install logrotate
  apt:
    name: logrotate
    state: present
- name: Copy logrotate config
  copy:
    src: logrotate.d/hummingbird
    dest: /etc/logrotate.d/hummingbird
    mode: 0644
- name: Restart rsyslog
  service:
    name: rsyslog
    enabled: yes
    state: restarted
- name: Create /var/run/hummingbird
  file:
    path: /var/run/hummingbird
    state: directory
    mode: 0755
    owner: hummingbird
    group: hummingbird
- name: create /srv/hummingbird
  file:
    path: /srv/hummingbird
    state: directory
    mode: 0755
    owner: hummingbird
    group: hummingbird
