---
- name: Create XFS partitions
  parted:
    device: /dev/{{item}}
    label: gpt
    number: 1
    part_type: primary
    state: present
  with_items: "{{ obj_devs }}"
- name: Unmount filesystems
  mount:
    path: /srv/node/{{item}}1
    state: absent
  with_items: "{{ obj_devs }}"
  when: reset == "yes"
- name: Create XFS filesystems
  filesystem:
    fstype: xfs
    dev: /dev/{{item}}1
    force: "{{ reset }}"
  with_items: "{{ obj_devs }}"
- name: Create dirs for mounts
  file:
    path: /srv/node/{{item}}1
    state: directory
    mode: 0755
    owner: root
    group: root
  with_items: "{{ obj_devs }}"
- name: Mount filesystems
  mount:
    path: /srv/node/{{item}}1
    src: /dev/{{item}}1
    fstype: xfs
    opts: "noatime,nodiratime,nobarrier"
    state: mounted
  with_items: "{{ obj_devs }}"
- name: Set permissions of mounted dirs
  file:
    path: /srv/node/{{item}}1
    owner: hummingbird
    group: hummingbird
  with_items: "{{ obj_devs }}"
